NAME_PROJECT: LindMOD

rd_seed: 1
log_dir: 'log'

model:
  voxel_num_limit: [64,64,64]
  unit_voxel_extent: [0.005, 0.005, 0.005]
  voxelization_mode: 4

  dropout_p: 0.015
  use_bn: True
  pool_type: avg

train:
  optimizer:
    name : Adam
    lr   : 0.01
    betas: [0.5, 0.999]
    eps  : 0.000001

  lr_scheduler:
    name: StepLR
    step_size: 1
    gamma: 0.5

  dataset:
    name: linemod
    npoint: 1024
    num_batch_per_epoch: 3000

  dataloader:
    bs: 64
    num_workers: 32
    shuffle: True
    drop_last: True
    pin_memory: False
  
  loss: None

  max_epoch: 10
  iterations_to_write: 50
  epochs_to_save: 2

test:
  dataset:
    name: linemod
    npoint: 1024
    num_img_per_epoch: -1

  dataloader:
    bs: 32
    num_workers: 32
    shuffle: False
    drop_last: False
    pin_memory: False  